wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.9.5
    t:
      1:
      - 1
      - 9
      2:
      - 1
      - 9
      3:
      - 7
      4: 3.9.5
      5: 0.10.33
      8:
      - 5
memory_bank_size:
  desc: null
  value: 2048
nmb_proto:
  desc: null
  value: 30
num_negatives:
  desc: null
  value: 512
temp:
  desc: null
  value: 0.1
warmup_epochs:
  desc: null
  value: 50
